"""Cascade delete Parameter-Pair

Revision ID: 4e6c8c286bd3
Revises: f063ea44c853
Create Date: 2024-09-17 16:26:09.156157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e6c8c286bd3'
down_revision: Union[str, None] = 'f063ea44c853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
