"""Restart

Revision ID: a857df63680b
Revises: eab3c723deaf
Create Date: 2024-10-08 22:23:29.571109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a857df63680b'
down_revision: Union[str, None] = 'eab3c723deaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasetparameterpairs', 'subset_id')
    op.add_column('datasets', sa.Column('parent_dataset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'datasets', 'datasets', ['parent_dataset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'datasets', type_='foreignkey')
    op.drop_column('datasets', 'parent_dataset_id')
    op.add_column('datasetparameterpairs', sa.Column('subset_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
