"""Fix Subset-Pairs

Revision ID: eab3c723deaf
Revises: efebb72390ea
Create Date: 2024-10-08 20:08:06.781110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab3c723deaf'
down_revision: Union[str, None] = 'efebb72390ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasetparameterpairs', sa.Column('subset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'datasetparameterpairs', 'datasubsets', ['subset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'datasetparameterpairs', type_='foreignkey')
    op.drop_column('datasetparameterpairs', 'subset_id')
    # ### end Alembic commands ###
