"""Add subsets

Revision ID: ee908988c3ef
Revises: f752ffe0a062
Create Date: 2024-10-08 19:43:43.707230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee908988c3ef'
down_revision: Union[str, None] = 'f752ffe0a062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasubsets', sa.Column('dataset_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'datasubsets', 'datasets', ['dataset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'datasubsets', type_='foreignkey')
    op.drop_column('datasubsets', 'dataset_id')
    # ### end Alembic commands ###
