"""Add subsets

Revision ID: f752ffe0a062
Revises: 4e6c8c286bd3
Create Date: 2024-10-08 19:38:31.422105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f752ffe0a062'
down_revision: Union[str, None] = '4e6c8c286bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subsets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subsets',
    sa.Column('pair_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_subset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['data_subset_id'], ['datasubsets.id'], name='subsets_data_subset_id_fkey'),
    sa.ForeignKeyConstraint(['pair_id'], ['datasetparameterpairs.id'], name='subsets_pair_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='subsets_pkey')
    )
    # ### end Alembic commands ###
